### ISSUE TITLE
Conformance requirements on $expand

### ISSUE THREAD

**Issue by jmandel** [HL7/US-Core-R4#21]
https://build.fhir.org/ig/HL7/US-Core-R4/clinical-notes-guidance.html#using-expand isn't linked to from the profiles, and it's unclear whether servers are required to support `$expand`. (And if so, on all `context` values, or just on a few specific ones?)

Without `$expand`, a client has no way to query for all `DiagnosticReport` resources, since `GET /DiagnosticReport?patient=[]` is not defined (the only query requires a `patient` and a `code`, and a client has no way to know/guess all possible codes that a server might be using, without `$expand`). Even with `$expand` it's not clear whether this operation would be required to return all codes used across all DiagnosticReports available across all  Patient records, or just a kind of "preferred" list (in which case, again clients would have no way to locate all DiagnosticReports).

**Comment by brettmarquard** [comment]
Will add SHOULD support to DocumentReference and DiagnosticReport

**Comment by Healthedata1** [comment]
added SHOULD Support to ValueSet in capstatement.  Need to review to see if needs to be more specific.  i.e. add in context this is limited to.

**Comment by Healthedata1** [comment]
discuss on 9/11 Argo R4 call:  proposal GF#24089 to add query by patient
