### ISSUE TITLE
Define a query to retrieve all DiagnosticReports by patient

### ISSUE THREAD

**Issue by jmandel** [HL7/US-Core-R4#22]
There are several issues for clients looking to fetch all DiagnosticReports on a patient (see #21). The simplest and most robust fix would be to add a required query like `GET /DiagnosticReport?patient=[id]`.

**Comment by brettmarquard** [comment]
Will add to 9/11 Argonaut Data Query call and will add tracker if participants agree.

**Comment by Healthedata1** [comment]
discuss on 9/11 Argo R4 call:  proposal GF#24089 to add query by patient
