### ISSUE TITLE
Patient.ethnicity/Patient.race/(others?) not modeled as CodableConcepts?

### ISSUE THREAD

**Issue by fiendish** [HL7/US-Core-R4#29]
It looks like some attribute extensions mimic CodableConcept types. For example, `ombCategory` and `detailed` in `us-core-race` are modeled as containing a string and a Coding. The CodeableConcept data type has a string element and a list of Codings. Is there a reason why these extensions aren't modeled using CodableConcept or is it purely historical? If historical, is there a plan to migrate them to use CodableConcepts? If there was a reason for specifically _not_ using CodeableConcept, is there some documentation of that decision we'd be able to reference?

**Comment by Healthedata1** [comment]
No, there is no plan see Jira tracker. FHIR-19925
<https://jira.hl7.org/browse/FHIR-19925>  Can  you withdraw this tracker?


Eric

Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
ehaas@healthedatainc.com

**Comment by fiendish** [comment]
That Jira track dismisses only "a single CodeableConcept" but doesn't address whether a list of CodeableConcepts would more idiomatically represent the information.
